# Tenant file for demotest10, autogenerated by python tool.
data "aws_ssm_parameter" "demotest10_tenant_admin_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest10-tenant-admin-iam-role-list"
}

data "aws_ssm_parameter" "demotest10_tenant_poweruser_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest10-tenant-poweruser-iam-role-list"
}

data "aws_ssm_parameter" "demotest10_tenant_viewonly_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest10-tenant-viewonly-iam-role-list"
}

locals {
  demotest10_tenant_admin_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest10_tenant_admin_iam_role_list.value)}"]
  demotest10_tenant_poweruser_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest10_tenant_poweruser_iam_role_list.value)}"]
  demotest10_tenant_viewonly_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest10_tenant_viewonly_iam_role_list.value)}"]
}

module "tenant_demotest10_prod" {
  source = "../member_account"

  name = "tenant_demotest10_prod"
  email = "jasong.miller+demotest10prod@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest10_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest10_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest10_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest10_mgmt" {
  source = "../member_account"

  name = "tenant_demotest10_mgmt"
  email = "jasong.miller+demotest10mgmt@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest10_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest10_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest10_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest10_staging" {
  source = "../member_account"

  name = "tenant_demotest10_staging"
  email = "jasong.miller+demotest10staging@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest10_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest10_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest10_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest10_dev" {
  source = "../member_account"

  name = "tenant_demotest10_dev"
  email = "jasong.miller+demotest10dev@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest10_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest10_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest10_tenant_viewonly_iam_role_list}"]
}

module "demotest10_budget" {
  source = "../budget"

  name = "demotest10"

  budget_notifications = [
    {
      protocol = "email"
      endpoint = "jasong.miller+budget@gsa.gov"
    }
  ]

  account_ids = [
    "${module.tenant_demotest10_prod.account_id}",
    "${module.tenant_demotest10_mgmt.account_id}",
    "${module.tenant_demotest10_staging.account_id}",
    "${module.tenant_demotest10_dev.account_id}",
  ]
}

# IAM role permission section - have to give sts-assume-role permission to users to allow them to switch to the roles.

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest10_prod" {
  provider = "aws.authlanding"
  name = "demotest10_prod_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest10_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_prod.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest10_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_admin_iam_role_list)}"
  user = "${local.demotest10_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest10_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest10_prod" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_prod_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest10_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_prod.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest10_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest10_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest10_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest10_prod" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_prod_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest10_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_prod.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest10_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest10_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest10_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest10_mgmt" {
  provider = "aws.authlanding"
  name = "demotest10_mgmt_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest10_mgmt account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_mgmt.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest10_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_admin_iam_role_list)}"
  user = "${local.demotest10_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest10_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest10_mgmt" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_mgmt_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest10_mgmtaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_mgmt.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest10_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest10_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest10_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest10_mgmt" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_mgmt_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest10_mgmtaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_mgmt.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest10_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest10_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest10_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest10_staging" {
  provider = "aws.authlanding"
  name = "demotest10_staging_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest10_staging account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_staging.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest10_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_admin_iam_role_list)}"
  user = "${local.demotest10_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest10_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest10_staging" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_staging_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest10_stagingaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_staging.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest10_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest10_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest10_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest10_staging" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_staging_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest10_stagingaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_staging.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest10_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest10_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest10_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest10_dev" {
  provider = "aws.authlanding"
  name = "demotest10_dev_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest10_dev account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_dev.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest10_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_admin_iam_role_list)}"
  user = "${local.demotest10_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest10_dev.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest10_dev" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_dev_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest10_devaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_dev.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest10_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest10_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest10_dev.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest10_dev" {
  provider = "aws.authlanding"
  name = "demotest10_demotest10_dev_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest10_devaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest10_dev.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest10_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest10_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest10_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest10_dev.arn}"
}

