# Tenant file for grace_monitoring, autogenerated by python tool.
data "aws_ssm_parameter" "grace_monitoring_tenant_admin_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "grace_monitoring-tenant-admin-iam-role-list"
}

data "aws_ssm_parameter" "grace_monitoring_tenant_poweruser_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "grace_monitoring-tenant-poweruser-iam-role-list"
}

data "aws_ssm_parameter" "grace_monitoring_tenant_viewonly_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "grace_monitoring-tenant-viewonly-iam-role-list"
}

locals {
  grace_monitoring_tenant_admin_iam_role_list = ["${split(",", data.aws_ssm_parameter.grace_monitoring_tenant_admin_iam_role_list.value)}"]
  grace_monitoring_tenant_poweruser_iam_role_list = ["${split(",", data.aws_ssm_parameter.grace_monitoring_tenant_poweruser_iam_role_list.value)}"]
  grace_monitoring_tenant_viewonly_iam_role_list = ["${split(",", data.aws_ssm_parameter.grace_monitoring_tenant_viewonly_iam_role_list.value)}"]
}

module "tenant_grace_monitoring_prod" {
  source = "../member_account"

  name = "tenant_grace_monitoring_prod"
  email = "manoj.chalise+devsecops@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.grace_monitoring_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.grace_monitoring_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.grace_monitoring_tenant_viewonly_iam_role_list}"]
}

module "grace_monitoring_budget" {
  source = "../budget"

  name = "grace_monitoring"

  budget_notifications = [
    {
      protocol = "email"
      endpoint = "manoj.chalise@gsa.gov"
    }
  ]

  account_ids = [
    "${module.tenant_grace_monitoring_prod.account_id}",
  #  "${module.tenant_grace_monitoring_mgmt.account_id}",
  ]
}





# IAM role permission section - have to give sts-assume-role permission to users to allow them to switch to the roles.

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_grace_monitoring_prod" {
  provider = "aws.authlanding"
  name = "grace_monitoring_prod_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this grace_monitoring_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_grace_monitoring_prod.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_grace_monitoring_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.grace_monitoring_tenant_admin_iam_role_list)}"
  user = "${local.grace_monitoring_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_grace_monitoring_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_grace_monitoring_prod" {
  provider = "aws.authlanding"
  name = "grace_monitoring_prod_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this grace_monitoring_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_grace_monitoring_prod.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_grace_monitoring_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.grace_monitoring_tenant_poweruser_iam_role_list)}"
  user = "${local.grace_monitoring_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_grace_monitoring_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_grace_monitoring_prod" {
  provider = "aws.authlanding"
  name = "grace_monitoring_prod_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this grace_monitoring_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_grace_monitoring_prod.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_grace_monitoring_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.grace_monitoring_tenant_viewonly_iam_role_list)}"
  user = "${local.grace_monitoring_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_grace_monitoring_prod.arn}"
}
