# Tenant file for demotest14, autogenerated by python tool.
data "aws_ssm_parameter" "demotest14_tenant_admin_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest14-tenant-admin-iam-role-list"
}

data "aws_ssm_parameter" "demotest14_tenant_poweruser_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest14-tenant-poweruser-iam-role-list"
}

data "aws_ssm_parameter" "demotest14_tenant_viewonly_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest14-tenant-viewonly-iam-role-list"
}

locals {
  demotest14_tenant_admin_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest14_tenant_admin_iam_role_list.value)}"]
  demotest14_tenant_poweruser_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest14_tenant_poweruser_iam_role_list.value)}"]
  demotest14_tenant_viewonly_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest14_tenant_viewonly_iam_role_list.value)}"]
}

module "tenant_demotest14_prod" {
  source = "../member_account"

  name = "tenant_demotest14_prod"
  email = "jasong.miller+demotest14prod@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest14_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest14_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest14_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest14_mgmt" {
  source = "../member_account"

  name = "tenant_demotest14_mgmt"
  email = "jasong.miller+demotest14mgmt@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest14_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest14_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest14_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest14_staging" {
  source = "../member_account"

  name = "tenant_demotest14_staging"
  email = "jasong.miller+demotest14staging@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest14_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest14_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest14_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest14_dev" {
  source = "../member_account"

  name = "tenant_demotest14_dev"
  email = "jasong.miller+demotest14dev@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest14_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest14_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest14_tenant_viewonly_iam_role_list}"]
}

module "demotest14_budget" {
  source = "../budget"

  name = "demotest14"

  budget_notifications = [
    {
      protocol = "email"
      endpoint = "jasong.miller+demotest14budget@gsa.gov"
    }
  ]

  account_ids = [
    "${module.tenant_demotest14_prod.account_id}",
    "${module.tenant_demotest14_mgmt.account_id}",
    "${module.tenant_demotest14_staging.account_id}",
    "${module.tenant_demotest14_dev.account_id}",
  ]
}

# IAM role permission section - have to give sts-assume-role permission to users to allow them to switch to the roles.

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest14_prod" {
  provider = "aws.authlanding"
  name = "demotest14_prod_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest14_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_prod.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest14_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_admin_iam_role_list)}"
  user = "${local.demotest14_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest14_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest14_prod" {
  provider = "aws.authlanding"
  name = "demotest14_prod_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest14_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_prod.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest14_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest14_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest14_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest14_prod" {
  provider = "aws.authlanding"
  name = "demotest14_prod_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest14_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_prod.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest14_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest14_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest14_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest14_mgmt" {
  provider = "aws.authlanding"
  name = "demotest14_mgmt_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest14_mgmt account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_mgmt.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest14_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_admin_iam_role_list)}"
  user = "${local.demotest14_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest14_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest14_mgmt" {
  provider = "aws.authlanding"
  name = "demotest14_mgmt_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest14_mgmtaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_mgmt.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest14_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest14_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest14_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest14_mgmt" {
  provider = "aws.authlanding"
  name = "demotest14_mgmt_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest14_mgmtaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_mgmt.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest14_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest14_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest14_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest14_staging" {
  provider = "aws.authlanding"
  name = "demotest14_staging_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest14_staging account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_staging.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest14_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_admin_iam_role_list)}"
  user = "${local.demotest14_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest14_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest14_staging" {
  provider = "aws.authlanding"
  name = "demotest14_staging_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest14_stagingaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_staging.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest14_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest14_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest14_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest14_staging" {
  provider = "aws.authlanding"
  name = "demotest14_staging_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest14_stagingaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_staging.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest14_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest14_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest14_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest14_dev" {
  provider = "aws.authlanding"
  name = "demotest14_dev_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest14_dev account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_dev.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest14_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_admin_iam_role_list)}"
  user = "${local.demotest14_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest14_dev.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest14_dev" {
  provider = "aws.authlanding"
  name = "demotest14_dev_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest14_devaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_dev.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest14_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest14_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest14_dev.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest14_dev" {
  provider = "aws.authlanding"
  name = "demotest14_dev_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest14_devaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest14_dev.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest14_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest14_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest14_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest14_dev.arn}"
}

