# Tenant file for gracesharedservices, autogenerated by python tool.
provider "aws" {
  alias = "sharedservices"

  assume_role {
    role_arn = "arn:aws:iam::${module.tenant_gracesharedservices_prod.account_id}:role/OrganizationAccountAccessRole"
  }
}

data "aws_ssm_parameter" "gracesharedservices_tenant_admin_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "gracesharedservices-tenant-admin-iam-role-list"
}

data "aws_ssm_parameter" "gracesharedservices_tenant_poweruser_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "gracesharedservices-tenant-poweruser-iam-role-list"
}

data "aws_ssm_parameter" "gracesharedservices_tenant_viewonly_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "gracesharedservices-tenant-viewonly-iam-role-list"
}

locals {
  gracesharedservices_tenant_admin_iam_role_list = ["${split(",", data.aws_ssm_parameter.gracesharedservices_tenant_admin_iam_role_list.value)}"]
  gracesharedservices_tenant_poweruser_iam_role_list = ["${split(",", data.aws_ssm_parameter.gracesharedservices_tenant_poweruser_iam_role_list.value)}"]
  gracesharedservices_tenant_viewonly_iam_role_list = ["${split(",", data.aws_ssm_parameter.gracesharedservices_tenant_viewonly_iam_role_list.value)}"]
}

module "tenant_gracesharedservices_prod" {
  source = "../member_account"

  name = "tenant_gracesharedservices_prod"
  email = "jasong.miller+sharedservicesprod@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.gracesharedservices_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.gracesharedservices_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.gracesharedservices_tenant_viewonly_iam_role_list}"]
  enable_member_guardduty = "true"
  guardduty_master_detector_id = "${aws_guardduty_detector.aws_guardduty_master.id}"
}

module "tenant_gracesharedservices_mgmt" {
  source = "../member_account"

  name = "tenant_gracesharedservices_mgmt"
  email = "jasong.miller+sharedservicesmgmt@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.gracesharedservices_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.gracesharedservices_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.gracesharedservices_tenant_viewonly_iam_role_list}"]
  enable_member_guardduty = "true"
  guardduty_master_detector_id = "${aws_guardduty_detector.aws_guardduty_master.id}"
}

module "gracesharedservices_budget" {
  source = "../budget"

  name = "gracesharedservices"

  budget_notifications = [
    {
      protocol = "email"
      endpoint = "jasong.miller+sharedservicesbudget@gsa.gov"
    }
  ]

  account_ids = [
    "${module.tenant_gracesharedservices_prod.account_id}",
    "${module.tenant_gracesharedservices_mgmt.account_id}",
  ]
}

# This account has a unique AMI builder user. Note that because there's no explicit secret store
# for GRACE to store secrets for IAM access, you will have to create an access key yourself in
# the web console (as of August 6, 2018)

resource "aws_iam_user" "packer_builder" {
  provider = "aws.sharedservices"
  name = "packer_builder"
}

resource "aws_iam_user_policy" "packer_builder_iam_policy" {
  provider = "aws.sharedservices"
  name = "packer_builder_ami_policy"
  user = "${aws_iam_user.packer_builder.name}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}

# IAM role permission section - have to give sts-assume-role permission to users to allow them to switch to the roles.

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_gracesharedservices_prod" {
  provider = "aws.authlanding"
  name = "gracesharedservices_prod_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this gracesharedservices_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_gracesharedservices_prod.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_gracesharedservices_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.gracesharedservices_tenant_admin_iam_role_list)}"
  user = "${local.gracesharedservices_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_gracesharedservices_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_gracesharedservices_prod" {
  provider = "aws.authlanding"
  name = "gracesharedservices_prod_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this gracesharedservices_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_gracesharedservices_prod.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_gracesharedservices_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.gracesharedservices_tenant_poweruser_iam_role_list)}"
  user = "${local.gracesharedservices_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_gracesharedservices_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_gracesharedservices_prod" {
  provider = "aws.authlanding"
  name = "gracesharedservices_prod_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this gracesharedservices_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_gracesharedservices_prod.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_gracesharedservices_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.gracesharedservices_tenant_viewonly_iam_role_list)}"
  user = "${local.gracesharedservices_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_gracesharedservices_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_gracesharedservices_mgmt" {
  provider = "aws.authlanding"
  name = "gracesharedservices_mgmt_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this gracesharedservices_mgmt account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_gracesharedservices_mgmt.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_gracesharedservices_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.gracesharedservices_tenant_admin_iam_role_list)}"
  user = "${local.gracesharedservices_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_gracesharedservices_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_gracesharedservices_mgmt" {
  provider = "aws.authlanding"
  name = "gracesharedservices_mgmt_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this gracesharedservices_mgmt account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_gracesharedservices_mgmt.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_gracesharedservices_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.gracesharedservices_tenant_poweruser_iam_role_list)}"
  user = "${local.gracesharedservices_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_gracesharedservices_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_gracesharedservices_mgmt" {
  provider = "aws.authlanding"
  name = "gracesharedservices_mgmt_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this gracesharedservices_mgmt account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_gracesharedservices_mgmt.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_gracesharedservices_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.gracesharedservices_tenant_viewonly_iam_role_list)}"
  user = "${local.gracesharedservices_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_gracesharedservices_mgmt.arn}"
}

# This tenant also has a lambda function that will query the tenant accounts in a sub OU to get the AWS accounts IDs.
# 08/08/18 by Jason Miller - jasong.miller@gsa.gov

resource "aws_s3_bucket" "tenant_info_bucket" {
  bucket = "grace-tenant-info"
  acl    = "private"

  tags {
    Purpose = "Stores information about the tenant subaccount IDs for other grace-core elements to use."
  }
}
resource "aws_iam_role" "tenant_account_lister_role" {
  name = "tenant-account-lister-role"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

# TODO: Tighten up this policy
resource "aws_iam_role_policy" "tenant_account_lister_role_policy" {
  name = "tenant_account_lister_role_policy"
  role = "${aws_iam_role.tenant_account_lister_role.id}"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}

data "archive_file" "lambda_tenant_account_lister_file" {
  type        = "zip"
  source_file = "${path.module}/files/tenant-account-lister.py"
  output_path = "${path.module}/files/tenant-account-lister.py.zip"
}

resource "aws_lambda_function" "lambda_tenant_account_lister_function" {
  filename      = "${path.module}/files/tenant-account-lister.py.zip"
  function_name = "tenant-account-lister"
  role          = "${aws_iam_role.tenant_account_lister_role.arn}"
  handler       = "tenant-account-lister.lambda_handler"
  runtime       = "python3.6"
}

resource "aws_cloudwatch_event_rule" "tenant_account_lister_event" {
  name                = "tenant-account-lister-run-hourly"
  description         = "Runs tenant account lister at the top of every hour"
  schedule_expression = "cron(1 * * * ? *)"
}

resource "aws_cloudwatch_event_target" "lambda_ebs_backup_function_event" {
  rule      = "${aws_cloudwatch_event_rule.tenant_account_lister_event.name}"
  target_id = "lambda_tenant_account_lister_function"
  arn       = "${aws_lambda_function.lambda_tenant_account_lister_function.arn}"
}

resource "aws_lambda_permission" "allow_cloudwatch_to_call_lambda_tenant_account_lister_function" {
  statement_id  = "AllowExecutionFromCloudWatch"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.lambda_tenant_account_lister_function.function_name}"
  principal     = "events.amazonaws.com"
  source_arn    = "${aws_cloudwatch_event_rule.tenant_account_lister_event.arn}"
}

# End tenant_account_lister lambda function resources