# Tenant file for demotest17, autogenerated by python tool.
data "aws_ssm_parameter" "demotest17_tenant_admin_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest17-tenant-admin-iam-role-list"
}

data "aws_ssm_parameter" "demotest17_tenant_poweruser_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest17-tenant-poweruser-iam-role-list"
}

data "aws_ssm_parameter" "demotest17_tenant_viewonly_iam_role_list" {
  provider = "aws.authlanding"

  # The name for this parameter must be unique to other tenants!
  name = "demotest17-tenant-viewonly-iam-role-list"
}

locals {
  demotest17_tenant_admin_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest17_tenant_admin_iam_role_list.value)}"]
  demotest17_tenant_poweruser_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest17_tenant_poweruser_iam_role_list.value)}"]
  demotest17_tenant_viewonly_iam_role_list = ["${split(",", data.aws_ssm_parameter.demotest17_tenant_viewonly_iam_role_list.value)}"]
}

module "tenant_demotest17_prod" {
  source = "../member_account"

  name = "tenant_demotest17_prod"
  email = "jasong.miller+demotest17prod@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest17_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest17_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest17_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest17_mgmt" {
  source = "../member_account"

  name = "tenant_demotest17_mgmt"
  email = "jasong.miller+demotest17mgmt@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest17_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest17_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest17_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest17_staging" {
  source = "../member_account"

  name = "tenant_demotest17_staging"
  email = "jasong.miller+demotest17staging@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest17_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest17_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest17_tenant_viewonly_iam_role_list}"]
}

module "tenant_demotest17_dev" {
  source = "../member_account"

  name = "tenant_demotest17_dev"
  email = "jasong.miller+demotest17dev@gsa.gov"
  authlanding_prod_account_id = "${module.authlanding_prod.account_id}"
  create_iam_roles = "true"

  tenant_admin_iam_role_list = ["${local.demotest17_tenant_admin_iam_role_list}"]
  tenant_poweruser_iam_role_list = ["${local.demotest17_tenant_poweruser_iam_role_list}"]
  tenant_viewonly_iam_role_list = ["${local.demotest17_tenant_viewonly_iam_role_list}"]
}

module "demotest17_budget" {
  source = "github.com/gsa/grace-tf-module-budget/terraform/modules/budget"

  name = "demotest17"

  budget_notifications = [
    {
      protocol = "email"
      endpoint = "jasong.miller+demotest17budget@gsa.gov"
    }
  ]

  account_ids = [
    "${module.tenant_demotest17_prod.account_id}",
    "${module.tenant_demotest17_mgmt.account_id}",
    "${module.tenant_demotest17_staging.account_id}",
    "${module.tenant_demotest17_dev.account_id}",
  ]
}

# IAM role permission section - have to give sts-assume-role permission to users to allow them to switch to the roles.

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest17_prod" {
  provider = "aws.authlanding"
  name = "demotest17_prod_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest17_prod account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_prod.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest17_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_admin_iam_role_list)}"
  user = "${local.demotest17_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest17_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest17_prod" {
  provider = "aws.authlanding"
  name = "demotest17_prod_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest17_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_prod.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest17_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest17_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest17_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest17_prod" {
  provider = "aws.authlanding"
  name = "demotest17_prod_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest17_prodaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_prod.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest17_prod_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest17_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest17_prod.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest17_mgmt" {
  provider = "aws.authlanding"
  name = "demotest17_mgmt_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest17_mgmt account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_mgmt.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest17_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_admin_iam_role_list)}"
  user = "${local.demotest17_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest17_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest17_mgmt" {
  provider = "aws.authlanding"
  name = "demotest17_mgmt_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest17_mgmtaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_mgmt.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest17_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest17_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest17_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest17_mgmt" {
  provider = "aws.authlanding"
  name = "demotest17_mgmt_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest17_mgmtaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_mgmt.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest17_mgmt_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest17_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest17_mgmt.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest17_staging" {
  provider = "aws.authlanding"
  name = "demotest17_staging_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest17_staging account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_staging.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest17_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_admin_iam_role_list)}"
  user = "${local.demotest17_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest17_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest17_staging" {
  provider = "aws.authlanding"
  name = "demotest17_staging_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest17_stagingaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_staging.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest17_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest17_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest17_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest17_staging" {
  provider = "aws.authlanding"
  name = "demotest17_staging_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest17_stagingaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_staging.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest17_staging_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest17_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest17_staging.arn}"
}

resource "aws_iam_policy" "sts_assume_admin_role_user_policy_demotest17_dev" {
  provider = "aws.authlanding"
  name = "demotest17_dev_admin_assume_role_user_policy"
  description = "Allows this user to assume the admin role in this demotest17_dev account"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_dev.tenant_admin_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_admin_role_user_policy_demotest17_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_admin_iam_role_list)}"
  user = "${local.demotest17_tenant_admin_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_admin_role_user_policy_demotest17_dev.arn}"
}

resource "aws_iam_policy" "sts_assume_poweruser_role_user_policy_demotest17_dev" {
  provider = "aws.authlanding"
  name = "demotest17_dev_poweruser_assume_role_user_policy"
  description = "Allows this user to assume the poweruser role in this demotest17_devaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_dev.tenant_poweruser_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_poweruser_role_user_policy_demotest17_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_poweruser_iam_role_list)}"
  user = "${local.demotest17_tenant_poweruser_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_poweruser_role_user_policy_demotest17_dev.arn}"
}

resource "aws_iam_policy" "sts_assume_viewonly_role_user_policy_demotest17_dev" {
  provider = "aws.authlanding"
  name = "demotest17_dev_viewonly_assume_role_user_policy"
  description = "Allows this user to assume the viewonly role in this demotest17_devaccount"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
     {
       "Effect": "Allow",
       "Resource": "${module.tenant_demotest17_dev.tenant_viewonly_role_arn}",
       "Action": "sts:AssumeRole"
     }
   ]
}
EOF
}

resource "aws_iam_user_policy_attachment" "sts_assume_viewonly_role_user_policy_demotest17_dev_attachment" {
  provider = "aws.authlanding"
  count = "${length(local.demotest17_tenant_viewonly_iam_role_list)}"
  user = "${local.demotest17_tenant_viewonly_iam_role_list[count.index]}"
  policy_arn = "${aws_iam_policy.sts_assume_viewonly_role_user_policy_demotest17_dev.arn}"
}

